version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server.log:/server.log
      - ./Error.log:/Error.log
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
